services:
  mongodb:
    image: mongo:4.4
    container_name: mongodb
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: productsdb
    volumes:
      - mongodb-data-v2:/data/db

volumes:
  mongodb-data-v2:
