apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo-config
  labels:
    app: tempo
data:
  tempo.yml: |
    server:
      http_listen_port: 3200

    distributor:
      receivers:
        zipkin:

    storage:
      trace:
        backend: local
        local:
          path: /tmp/tempo/blocks
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tempo
  labels:
    app: tempo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tempo
  template:
    metadata:
      labels:
        app: tempo
    spec:
      containers:
      - name: tempo
        image: grafana/tempo:2.2.2
        args: ["-config.file=/etc/tempo.yml"]
        ports:
        - containerPort: 3200
        - containerPort: 9411
        volumeMounts:
        - name: tempo-config
          mountPath: /etc/tempo.yml
          subPath: tempo.yml
      volumes:
      - name: tempo-config
        configMap:
          name: tempo-config
---
apiVersion: v1
kind: Service
metadata:
  name: tempo
  labels:
    app: tempo
spec:
  selector:
    app: tempo
  ports:
  - name: tempo-http
    port: 3200
    targetPort: 3200
    protocol: TCP
  - name: zipkin
    port: 9411
    targetPort: 9411
    protocol: TCP

